import { Footer } from '@/components/Footer';
import { Toaster } from '@/components/ui/toaster';
import { AuthProvider } from '@/providers/AuthProvider';
import StoreProvider from '@/providers/StoreProvider';
import type { Metadata } from 'next';
import { Poly } from 'next/font/google';
import './globals.css';

export const poly = Poly({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-poly',
});

export const metadata: Metadata = {
  title: 'Perpustakaan Online',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poly.className}>
        <StoreProvider>
          <AuthProvider>
            <Toaster />
            {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
